export const INVALID_PHONE_NUMBER_OR_CODE = 'INVALID_PHONE_NUMBER_OR_CODE';
export const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
export const INVALID_CODE = 'INVALID_CODE';
export const REQUEST_CONFIRM_CODE_LIMIT = 'REQUEST_CONFIRM_CODE_LIMIT';
export const MUST_BE_LETTERS_AND_NUMBERS = 'MUST_BE_LETTERS_AND_NUMBERS';
export const PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT';
export const PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG';
export const INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD';
export const NOT_ACCEPTABLE = 'NOT_ACCEPTABLE';
export const MAX_NAME_LENGTH = 'MAX_NAME_LENGTH';
export const EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const MAIN_NOT_CONFIRMED = 'MAIN_NOT_CONFIRMED';
export const YOUR_ACCOUNT_IS_NOT_APPROVED_YET =
  'YOUR_ACCOUNT_IS_NOT_APPROVED_YET';

